import React, { useState } from 'react';

/*
  PUBLIC_INTERFACE
*/
/**
 * AI-powered ItineraryPage: Lets user enter trip preferences and generates an itinerary.
 * Demonstrates secure loading of API keys from environment variables.
 * Example usage:
 *   const amadeusApiKey = process.env.REACT_APP_AMADEUS_API_KEY;
 *   const amadeusApiSecret = process.env.REACT_APP_AMADEUS_API_SECRET;
 * Replace the mock API call with your preferred LLM/AI provider.
 */
function ItineraryPage() {
  const [form, setForm] = useState({
    destination: '',
    startDate: '',
    endDate: '',
    budget: '',
    preferences: ''
  });
  const [loading, setLoading] = useState(false);
  const [itinerary, setItinerary] = useState(null);
  const [error, setError] = useState(null);

  // Securely load API keys
  const amadeusApiKey = 'I3Qf2ShydSGU7hDgLDG3IAl3hHO5QJwt'
  //process.env.REACT_APP_AMADEUS_API_KEY; // Loaded from .env (NOT visible to browser JS console)
  const amadeusApiSecret ='0FMhmIHl7JHsbFpy' 
  //process.env.REACT_APP_AMADEUS_API_SECRET;

  // Handler for form field changes
  function handleChange(e) {
    setForm({ ...form, [e.target.name]: e.target.value });
  }

  // Handler for submitting the itinerary request
  async function handleSubmit(e) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setItinerary(null);
    // In production, you would POST to your backend (never expose keys in the browser), or a proxy.
    // For demo, we show using the env variable (DO NOT expose secrets in client bundle for real providers).
    try {
      // This simulates an AI/LLM endpoint using env keys (mock)
      const resp = await new Promise((resolve) => {
        setTimeout(() => {
          resolve({
            plan: [
              `Day 1: Arrive in ${form.destination}, enjoy a city tour.`,
              `Day 2: Explore local attractions based on your preferences: ${form.preferences}.`,
              `Day 3: Wrap up with a special experience within your ${form.budget} budget!`
            ],
            ai: 'TravelGenieAI',
            usedKey: amadeusApiKey && amadeusApiKey.slice(0,4) + '...'
          });
        }, 900);
      });
      setItinerary(resp);
    } catch (err) {
      setError('Failed to generate itinerary. Please try again.');
    }
    setLoading(false);
  }

  return (
    <div>
      <h2>AI Itinerary Planner</h2>
      <p>
        Provide your travel details. We use AI to generate a custom itinerary.<br />
        <span style={{fontSize:"0.94em", color:"var(--text-secondary)"}}>
          (API keys are securely loaded from <b>process.env</b> at build time; see <code>.env.example</code>.)
        </span>
      </p>
      <form onSubmit={handleSubmit} style={{ maxWidth: 500, margin: '30px auto', display: 'flex', flexDirection: 'column', gap: 18 }}>
        <input required type="text" name="destination" placeholder="Destination" value={form.destination} onChange={handleChange} />
        <div style={{display:'flex', gap:10}}>
          <input required type="date" name="startDate" value={form.startDate} onChange={handleChange} />
          <input required type="date" name="endDate" value={form.endDate} onChange={handleChange} />
        </div>
        <input required type="text" name="budget" placeholder="Budget (e.g., $1000)" value={form.budget} onChange={handleChange} />
        <input type="text" name="preferences" placeholder="Preferences (e.g., museums, nature, food)" value={form.preferences} onChange={handleChange} />
        <button disabled={loading} type="submit" className="btn btn-large">
          {loading ? "Generating..." : "Generate Itinerary"}
        </button>
      </form>

      {loading && <div>Loading AI plan...</div>}

      {error && <div style={{color:'red'}}>{error}</div>}
      {itinerary && (
        <div style={{marginTop: 32, border: '1px solid var(--border-color)', borderRadius: 8, padding: 20, background: '#111624'}}>
          <h3>Your Personalized Itinerary</h3>
          <ol>
            {itinerary.plan.map((step, idx) => (
              <li key={idx}>{step}</li>
            ))}
          </ol>
          <div style={{fontSize: "0.93em", color:"var(--text-secondary)"}}>
            (Generated by <b>{itinerary.ai}</b> using API key: <code>{itinerary.usedKey}</code>)
          </div>
        </div>
      )}
    </div>
  );
}

export default ItineraryPage;
